linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - unused
    - gosimple
    - ineffassign
    # Uncomment the following lines when using loglinter as a plugin locally:
    # - loglinter

# Uncomment when using loglinter as a plugin:
# linters-settings:
#   custom:
#     loglinter:
#       path: ./loglinter.so
#       description: Checks log messages for compliance with logging standards
#       original-url: github.com/dontpanicw/log-linter

issues:
  exclude-use-default: false
